### ISSUE TITLE
com.alipay.android.phone.messageboxstatic.biz.dao.TradeDao 没有hook到 不知道老兄能否基于指点一下

### ISSUE THREAD

**Issue by OneDayNoMore** [ruoxue/Alipayqq#2]

**Comment by ruoxue** [comment]
这个没啥意义

**Comment by OneDayNoMore** [comment]
我现在需要这个功能 不知道你能否指点一下

**Comment by OneDayNoMore** [comment]
这个功能做不出来 我就要走人了 老板下了死命令 还希望指点一下 为啥这个没有hook住，就算收到钱 也进不了这个方法

XposedBridge.hookAllMethods(XposedHelpers.findClass(Constans.ALI_SQL, loadPackageParam.classLoader), "insertMessageInfo", new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                super.afterHookedMethod(param);
                Log.i("tag","123");
                String str1 = (String) XposedHelpers.callMethod(param.args[0], "toString");

                String str2 = str1.replace("content='", "'");
                if ((str2.contains("二维码收款")) || (str2.contains("收到一笔转账"))) {
                    JSONObject localJSONObject = JSONObject.parseObject(str2);
                    String str3 = localJSONObject.getString("content").replace("￥", "");
                    String str4 = localJSONObject.getString("assistMsg2");
                    String str5 = str1.replace("tradeNO=", "&");
                    // g.a("收到支付宝支付订单：" + str5 + "==" + str3 + "==" + str4);
                    Intent localIntent = new Intent();
                    localIntent.putExtra(Constans.BILL_NO, str5);
                    localIntent.putExtra(Constans.BILL_MONEY, str3);
                    localIntent.putExtra(Constans.BILL_MARK, str4);
                    localIntent.putExtra(Constans.BILL_TYPE, Constans.ALIPAY);
                    localIntent.setAction(Constans.ACTION_PAY_SUCCESS);
                    ctx.sendBroadcast(localIntent);
                }

            }
        });
